apiVersion: apps/v1
kind: Deployment
metadata:
  name: super-utils
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: super-utils
  template:
    metadata:
      labels:
        app: super-utils
    spec:
      containers:
        - name: super-utils
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 8080
